/**
 * Skill icons mapping using react-icons Simple Icons (si).
 * Each key is the icon identifier stored in the database (e.g. "SiReact").
 * To add a new icon: import it from "react-icons/si" and add an entry below.
 */
import { IconType } from "react-icons";
import {
  // Languages
  SiJavascript,
  SiTypescript,
  SiPython,
  SiOpenjdk,
  SiCplusplus,
  SiC,
  SiRuby,
  SiPhp,
  SiSwift,
  SiKotlin,
  SiGo,
  SiRust,
  SiDart,
  SiR,
  SiScala,
  SiPerl,
  SiLua,
  SiHaskell,
  SiElixir,
  SiClojure,
  SiAssemblyscript,
  SiGnubash,

  // Frontend
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiNuxtdotjs,
  SiAngular,
  SiSvelte,
  SiHtml5,
  SiCss3,
  SiSass,
  SiTailwindcss,
  SiBootstrap,
  SiJquery,
  SiWebpack,
  SiVite,
  SiStyledcomponents,
  SiFramer,
  SiRedux,
  SiFlutter,
  SiAndroid,
  SiElectron,
  SiThreedotjs,

  // Backend
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiFastify,
  SiDjango,
  SiFlask,
  SiFastapi,
  SiSpringboot,
  SiRubyonrails,
  SiLaravel,
  SiDotnet,
  SiSharp,
  SiGraphql,
  SiApollographql,
  SiTrpc,
  SiPrisma,

  // Databases
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiSqlite,
  SiMariadb,
  SiElasticsearch,
  SiFirebase,
  SiSupabase,
  SiAmazondynamodb,
  SiNeo4J,

  // DevOps & Tools
  SiDocker,
  SiKubernetes,
  SiGit,
  SiGithub,
  SiGitlab,
  SiBitbucket,
  SiJenkins,
  SiGithubactions,
  SiCircleci,
  SiTravisci,
  SiTerraform,
  SiAnsible,
  SiNginx,
  SiApache,
  SiLinux,
  SiUbuntu,
  SiAmazonwebservices,
  SiGooglecloud,
  SiDigitalocean,
  SiVercel,
  SiNetlify,
  SiHeroku,
  SiCloudflare,
  SiGrafana,
  SiPrometheus,
  SiJira,
  SiConfluence,
  SiSlack,
  SiPostman,
  SiFigma,
  SiNotion,
  SiIntellijidea,
  SiAdobeacrobatreader,
  SiAdobeaudition,
  SiVscodium,

  // AI & Data
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiKeras,
  SiOpencv,
  SiJupyter,
  SiNumpy,
  SiPandas,
  SiApachespark,
  SiApachekafka,
  SiOpenai,
  SiHuggingface,
  SiLangchain,

  // Testing
  SiJest,
  SiCypress,
  SiSelenium,
  SiVitest,

  // Other
  SiWordpress,
  SiShopify,
  SiStripe,
  SiAuth0,
  SiJsonwebtokens,
  SiSocketdotio,
  SiRabbitmq,
  SiMarkdown,
  SiNpm,
  SiYarn,
  SiPnpm,
} from "react-icons/si";
import { VscCode } from "react-icons/vsc";

/**
 * Map of icon identifier -> React Icon component.
 * The key is what gets stored in the database.
 */
export const SKILL_ICON_MAP: Record<string, IconType> = {
  // Languages
  SiJavascript,
  SiTypescript,
  SiPython,
  SiOpenjdk,
  SiCplusplus,
  SiC,
  SiRuby,
  SiPhp,
  SiSwift,
  SiKotlin,
  SiGo,
  SiRust,
  SiDart,
  SiR,
  SiScala,
  SiPerl,
  SiLua,
  SiHaskell,
  SiElixir,
  SiClojure,
  SiAssemblyscript,
  SiGnubash,

  // Frontend
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiNuxtdotjs,
  SiAngular,
  SiSvelte,
  SiHtml5,
  SiCss3,
  SiSass,
  SiTailwindcss,
  SiBootstrap,
  SiJquery,
  SiWebpack,
  SiVite,
  SiStyledcomponents,
  SiFramer,
  SiRedux,
  SiFlutter,
  SiAndroid,
  SiElectron,
  SiThreedotjs,

  // Backend
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiFastify,
  SiDjango,
  SiFlask,
  SiFastapi,
  SiSpringboot,
  SiRubyonrails,
  SiLaravel,
  SiDotnet,
  SiSharp,
  SiGraphql,
  SiApollographql,
  SiTrpc,
  SiPrisma,

  // Databases
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiSqlite,
  SiMariadb,
  SiElasticsearch,
  SiFirebase,
  SiSupabase,
  SiAmazondynamodb,
  SiNeo4J,

  // DevOps & Tools
  SiDocker,
  SiKubernetes,
  SiGit,
  SiGithub,
  SiGitlab,
  SiBitbucket,
  SiJenkins,
  SiGithubactions,
  SiCircleci,
  SiTravisci,
  SiTerraform,
  SiAnsible,
  SiNginx,
  SiApache,
  SiLinux,
  SiUbuntu,
  SiAmazonwebservices,
  SiGooglecloud,
  SiDigitalocean,
  SiVercel,
  SiNetlify,
  SiHeroku,
  SiCloudflare,
  SiGrafana,
  SiPrometheus,
  SiJira,
  SiConfluence,
  SiSlack,
  SiPostman,
  SiFigma,
  SiNotion,
  SiIntellijidea,
  SiAdobeacrobatreader,
  SiAdobeaudition,
  SiVscodium,

  // AI & Data
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiKeras,
  SiOpencv,
  SiJupyter,
  SiNumpy,
  SiPandas,
  SiApachespark,
  SiApachekafka,
  SiOpenai,
  SiHuggingface,
  SiLangchain,

  // Testing
  SiJest,
  SiCypress,
  SiSelenium,
  SiVitest,

  // Other
  SiWordpress,
  SiShopify,
  SiStripe,
  SiAuth0,
  SiJsonwebtokens,
  SiSocketdotio,
  SiRabbitmq,
  SiMarkdown,
  SiNpm,
  SiYarn,
  SiPnpm,
  VscCode,
};

/** Brand colors for technology icons */
export const SKILL_ICON_COLORS: Record<string, string> = {
  SiJavascript: "#F7DF1E",
  SiTypescript: "#3178C6",
  SiPython: "#3776AB",
  SiOpenjdk: "#437291",
  SiCplusplus: "#00599C",
  SiC: "#A8B9CC",
  SiRuby: "#CC342D",
  SiPhp: "#777BB4",
  SiGo: "#00ADD8",
  SiRust: "#000000",
  SiReact: "#61DAFB",
  SiNextdotjs: "#000000",
  SiVuedotjs: "#4FC08D",
  SiAngular: "#DD0031",
  SiSvelte: "#FF3E00",
  SiHtml5: "#E34F26",
  SiCss3: "#1572B6",
  SiSass: "#CC6699",
  SiTailwindcss: "#06B6D4",
  SiNodedotjs: "#339933",
  SiExpress: "#000000",
  SiDjango: "#092E20",
  SiPostgresql: "#4169E1",
  SiMysql: "#4479A1",
  SiMongodb: "#47A248",
  SiRedis: "#DC382D",
  SiDocker: "#2496ED",
  SiGit: "#F05032",
  SiGithub: "#181717",
  SiAmazonwebservices: "#232F3E",
  SiVercel: "#000000",
  SiFigma: "#F24E1E",
  SiTensorflow: "#FF6F00",
  SiPytorch: "#EE4C2C",
  SiJest: "#C21325",
  SiAndroid: "#3DDC84",
  SiSharp: "#239120",
  SiGradle: "#02303A",
  SiLangchain: "#1C3C3C",
  VscCode: "#007ACC",
  SiJira: "#0052CC",
};

/** Get the brand color for an icon, or null for default */
export function getSkillIconColor(iconKey: string | null | undefined): string | null {
  if (!iconKey) return null;
  return SKILL_ICON_COLORS[iconKey] ?? null;
}

/** Get the icon component for a given identifier, or null if not found */
export function getSkillIcon(iconKey: string | null | undefined): IconType | null {
  if (!iconKey) return null;
  return SKILL_ICON_MAP[iconKey] ?? null;
}

/** Special display names for icons (SiOpenjdk -> Java, etc.) */
const ICON_LABELS: Record<string, string> = {
  SiOpenjdk: "Java",
  SiSharp: "C#",
  VscCode: "VS Code",
};

/** Extra search terms so "java" or "openjdk" finds Java, etc. */
const SEARCH_ALIASES: Record<string, string[]> = {
  SiOpenjdk: ["java", "openjdk", "jaba"],
  SiSharp: ["csharp", "c#", "asp.net"],
  SiAndroid: ["android"],
  VscCode: ["vscode", "vs code", "visual studio code"],
  SiLangchain: ["langchain", "lang chain"],
  SiAdobeacrobatreader: ["pdf", "adobe"],
  SiAdobeaudition: ["audio"],
  SiNodedotjs: ["node", "nodejs"],
  SiNextdotjs: ["next", "nextjs"],
  SiVuedotjs: ["vue", "vuejs"],
  SiNuxtdotjs: ["nuxt", "nuxtjs"],
};

/** Map skill name (normalized lowercase) to icon key - for auto-matching when typing */
const SKILL_NAME_TO_ICON: Record<string, string> = {
  // Languages
  java: "SiOpenjdk",
  hvava: "SiOpenjdk",
  openjdk: "SiOpenjdk",
  javascript: "SiJavascript",
  js: "SiJavascript",
  typescript: "SiTypescript",
  ts: "SiTypescript",
  python: "SiPython",
  py: "SiPython",
  c: "SiC",
  "c#": "SiSharp",
  csharp: "SiSharp",
  "c++": "SiCplusplus",
  cpp: "SiCplusplus",
  ruby: "SiRuby",
  php: "SiPhp",
  swift: "SiSwift",
  kotlin: "SiKotlin",
  go: "SiGo",
  golang: "SiGo",
  rust: "SiRust",
  dart: "SiDart",
  r: "SiR",
  scala: "SiScala",
  perl: "SiPerl",
  lua: "SiLua",
  haskell: "SiHaskell",
  elixir: "SiElixir",
  // Frontend
  react: "SiReact",
  reactjs: "SiReact",
  "react js": "SiReact",
  "react.js": "SiReact",
  nextjs: "SiNextdotjs",
  "next.js": "SiNextdotjs",
  vue: "SiVuedotjs",
  vuejs: "SiVuedotjs",
  nuxt: "SiNuxtdotjs",
  angular: "SiAngular",
  svelte: "SiSvelte",
  html: "SiHtml5",
  html5: "SiHtml5",
  htmlcss: "SiHtml5",
  "html/css": "SiHtml5",
  css: "SiCss3",
  css3: "SiCss3",
  sass: "SiSass",
  tailwind: "SiTailwindcss",
  tailwindcss: "SiTailwindcss",
  bootstrap: "SiBootstrap",
  jquery: "SiJquery",
  webpack: "SiWebpack",
  vite: "SiVite",
  redux: "SiRedux",
  flutter: "SiFlutter",
  android: "SiAndroid",
  electron: "SiElectron",
  threejs: "SiThreedotjs",
  "three.js": "SiThreedotjs",
  // Backend
  node: "SiNodedotjs",
  nodejs: "SiNodedotjs",
  "node js": "SiNodedotjs",
  "node.js": "SiNodedotjs",
  express: "SiExpress",
  nestjs: "SiNestjs",
  django: "SiDjango",
  flask: "SiFlask",
  fastapi: "SiFastapi",
  springboot: "SiSpringboot",
  "spring boot": "SiSpringboot",
  laravel: "SiLaravel",
  blade: "SiLaravel",
  aspnet: "SiDotnet",
  aspnetmvc: "SiDotnet",
  "asp.net": "SiDotnet",
  "asp.net mvc": "SiDotnet",
  dotnet: "SiDotnet",
  graphql: "SiGraphql",
  prisma: "SiPrisma",
  // Databases
  postgresql: "SiPostgresql",
  postgres: "SiPostgresql",
  sql: "SiPostgresql",
  mysql: "SiMysql",
  mongodb: "SiMongodb",
  mongo: "SiMongodb",
  redis: "SiRedis",
  sqlite: "SiSqlite",
  firebase: "SiFirebase",
  supabase: "SiSupabase",
  // DevOps & Tools
  docker: "SiDocker",
  dockers: "SiDocker",
  kubernetes: "SiKubernetes",
  k8s: "SiKubernetes",
  git: "SiGit",
  github: "SiGithub",
  gitlab: "SiGitlab",
  bitbucket: "SiBitbucket",
  jenkins: "SiJenkins",
  aws: "SiAmazonwebservices",
  amazonwebservices: "SiAmazonwebservices",
  vercel: "SiVercel",
  netlify: "SiNetlify",
  heroku: "SiHeroku",
  cloudflare: "SiCloudflare",
  figma: "SiFigma",
  postman: "SiPostman",
  jira: "SiJira",
  gradle: "SiGradle",
  vscode: "VscCode",
  "vs code": "VscCode",
  linux: "SiLinux",
  bash: "SiGnubash",
  linuxbash: "SiLinux",
  "linux/bash": "SiLinux",
  jwt: "SiJsonwebtokens",
  restapi: "SiJsonwebtokens",
  "rest api": "SiJsonwebtokens",
  restapis: "SiJsonwebtokens",
  "rest apis": "SiJsonwebtokens",
  // AI & Data
  tensorflow: "SiTensorflow",
  pytorch: "SiPytorch",
  keras: "SiKeras",
  jupyter: "SiJupyter",
  numpy: "SiNumpy",
  pandas: "SiPandas",
  openai: "SiOpenai",
  "openai api": "SiOpenai",
  openaiapi: "SiOpenai",
  langchain: "SiLangchain",
  pdf: "SiAdobeacrobatreader",
  pdfprocessing: "SiAdobeacrobatreader",
  "pdf processing": "SiAdobeacrobatreader",
  promptengineering: "SiOpenai",
  "prompt engineering": "SiOpenai",
  audioprocessing: "SiAdobeaudition",
  "audio processing": "SiAdobeaudition",
  // Testing
  jest: "SiJest",
  cypress: "SiCypress",
  selenium: "SiSelenium",
  vitest: "SiVitest",
};

/** Get icon key for a skill name (auto-match when typing). Returns null if no match. */
export function getIconForSkillName(name: string): string | null {
  if (!name || typeof name !== "string") return null;
  const trimmed = name.trim().toLowerCase();
  const normalized = trimmed.replace(/[\s.\-/]+/g, "");
  return SKILL_NAME_TO_ICON[trimmed] ?? SKILL_NAME_TO_ICON[normalized] ?? null;
}

/** Get all available icon entries for the picker (sorted alphabetically by display name) */
export function getAvailableIcons(): { key: string; label: string; searchTerms: string }[] {
  return Object.keys(SKILL_ICON_MAP)
    .map((key) => {
      const label =
        ICON_LABELS[key] ??
        key
          .replace(/^Si/, "")
          .replace(/dotjs$/i, ".js")
          .replace(/dotnet$/i, ".NET")
          .replace(/dotio$/i, ".io")
          .replace(/plusplus$/i, "++");
      const aliases = SEARCH_ALIASES[key] || [];
      const searchTerms = [label, key.replace(/^Si/, ""), ...aliases].join(" ").toLowerCase();
      return { key, label, searchTerms };
    })
    .sort((a, b) => a.label.localeCompare(b.label));
}
